### ISSUE TITLE
프로젝트 기획

### ISSUE THREAD

**Issue by e3hope** [TeamND/Daily#2]
# 스토리보드 참조

Link: https://docs.google.com/presentation/d/1-g5rDZenb58GePH3LoLWomqBi29qP5HCO-QZe4IV2HM/edit#slide=id.g1728cc95fbb_0_11

**Comment by seungyooooong** [comment]
기획서(시나리오) 작성 필요

**Comment by seungyooooong** [comment]
11/10 미팅 참조
