### ISSUE TITLE
12/1 미팅

### ISSUE THREAD

**Issue by e3hope** [TeamND/Daily#20]
1. repeat/count -> count/order
2. goal count column add
3. goal rating 고민
4. goal start_time/end_time 제거
5. start/end시간찍어서 보내주기
6. 1회 시간 x check, 횟수 o count, 시간 o timer
7. issucces(목표달성률) 추가 / 일달성률은 계산해서 보내기
8. 년/ 일달성률만	월/ 일달성률+심볼+ issucces	 주 / 일당성률
9. user.info 날짜/반복 어떤타입인지 기본값 설정

**Comment by seungyooooong** [comment]
10. 목표 추가
     -> 연, 월, 주 달력에서 모두 목표 추가 팝업 접근 가능
     -> 목표 추가 시, 오늘 날짜의 주(일) 달력으로 이동
